In [54]:
import numpy as np
import csv

In [3]:
# a = np.genfromtxt('AAPL-2016.csv', dtype = dt, delimiter=',', skip_header = 1)
# b = np.genfromtxt('AAPL-2017.csv', dtype = dt, delimiter=',', skip_header = 1)
y = np.genfromtxt('AAPL-2016.csv', delimiter=',', skip_header = 1)
z = np.genfromtxt('AAPL-2017.csv', delimiter=',', skip_header = 1)

In [ ]:
print(y)
print(z)

In [5]:
# print(a.shape)
# print(b.shape)
print(y.shape)
print(z.shape)

(250, 7)
(251, 7)


In [6]:
z = np.delete(z,250,0)

In [7]:
print(y.shape)
print(z.shape)

(250, 7)
(250, 7)


In [22]:
open_2016 = y[:,[1]]

In [23]:
volume_2016 = y[:,[6]]

In [24]:
print(open_2016)

[[102.610001]
 [105.75    ]
 [100.559998]
 [ 98.68    ]
 [ 98.550003]
 [ 98.970001]
 [100.550003]
 [100.32    ]
 [ 97.959999]
 [ 96.199997]
 [ 98.410004]
 [ 95.099998]
 [ 97.059998]
 [ 98.629997]
 [101.519997]
 [ 99.93    ]
 [ 96.040001]
 [ 93.790001]
 [ 94.790001]
 [ 96.470001]
 [ 95.419998]
 [ 95.      ]
 [ 95.860001]
 [ 96.519997]
 [ 93.129997]
 [ 94.290001]
 [ 95.919998]
 [ 93.790001]
 [ 94.190002]
 [ 95.019997]
 [ 96.669998]
 [ 98.839996]
 [ 96.      ]
 [ 96.309998]
 [ 96.400002]
 [ 93.980003]
 [ 96.050003]
 [ 97.199997]
 [ 96.860001]
 [ 97.650002]
 [100.510002]
 [100.580002]
 [102.370003]
 [102.389999]
 [100.779999]
 [101.309998]
 [101.410004]
 [102.239998]
 [101.910004]
 [103.959999]
 [104.610001]
 [105.519997]
 [106.339996]
 [105.93    ]
 [105.25    ]
 [106.480003]
 [105.470001]
 [106.      ]
 [104.889999]
 [108.650002]
 [109.720001]
 [108.779999]
 [110.419998]
 [109.510002]
 [110.230003]
 [109.949997]
 [108.910004]
 [108.970001]
 [109.339996]
 [110.800003]
 [111.620003]
 [112.

In [20]:
print(volume_2016)

[[6.764940e+07]
 [5.579100e+07]
 [6.845740e+07]
 [8.109440e+07]
 [7.079800e+07]
 [4.973940e+07]
 [4.915420e+07]
 [6.243960e+07]
 [6.317010e+07]
 [7.901000e+07]
 [5.308770e+07]
 [7.233440e+07]
 [5.216150e+07]
 [6.580050e+07]
 [5.179450e+07]
 [7.507700e+07]
 [1.333697e+08]
 [5.567880e+07]
 [6.441650e+07]
 [4.094350e+07]
 [3.735720e+07]
 [4.596430e+07]
 [4.647170e+07]
 [4.641810e+07]
 [5.402140e+07]
 [4.433120e+07]
 [4.234360e+07]
 [5.007470e+07]
 [4.035140e+07]
 [4.905790e+07]
 [4.486320e+07]
 [3.902100e+07]
 [3.537420e+07]
 [3.428080e+07]
 [3.194260e+07]
 [3.625570e+07]
 [2.758270e+07]
 [2.899110e+07]
 [3.521630e+07]
 [5.040710e+07]
 [3.316960e+07]
 [3.695570e+07]
 [4.605510e+07]
 [3.582890e+07]
 [3.156190e+07]
 [2.720170e+07]
 [3.351360e+07]
 [2.740820e+07]
 [2.507610e+07]
 [4.006770e+07]
 [3.830350e+07]
 [3.442070e+07]
 [4.420520e+07]
 [3.550270e+07]
 [3.244440e+07]
 [2.570350e+07]
 [2.613300e+07]
 [1.941140e+07]
 [3.119010e+07]
 [4.560110e+07]
 [2.588840e+07]
 [2.587400e+07]
 [3.7356

In [26]:
open_2017 = z[:,[1]]

In [27]:
volume_2017 = z[:,[6]]

In [29]:
print(open_2017)

[[28.950001]
 [28.9625  ]
 [28.98    ]
 [29.195   ]
 [29.487499]
 [29.692499]
 [29.684999]
 [29.725   ]
 [29.7775  ]
 [29.584999]
 [30.      ]
 [29.85    ]
 [30.112499]
 [30.      ]
 [29.887501]
 [30.105   ]
 [30.4175  ]
 [30.535   ]
 [30.2325  ]
 [30.2875  ]
 [31.7575  ]
 [31.995001]
 [32.077499]
 [32.282501]
 [32.634998]
 [32.837502]
 [32.912498]
 [33.115002]
 [33.27    ]
 [33.3675  ]
 [33.880001]
 [33.9175  ]
 [33.775002]
 [34.057499]
 [34.107498]
 [34.345001]
 [33.977501]
 [34.285   ]
 [34.27    ]
 [34.4725  ]
 [35.      ]
 [34.695   ]
 [34.842499]
 [34.764999]
 [34.737499]
 [34.685001]
 [34.8125  ]
 [34.712502]
 [34.825001]
 [34.852501]
 [35.18    ]
 [35.25    ]
 [35.099998]
 [35.5275  ]
 [34.962502]
 [35.314999]
 [35.375   ]
 [34.8475  ]
 [35.227501]
 [35.919998]
 [36.047501]
 [35.93    ]
 [35.927502]
 [35.8125  ]
 [36.055   ]
 [36.072498]
 [35.932499]
 [35.900002]
 [35.735001]
 [35.400002]
 [35.477501]
 [35.369999]
 [35.352501]
 [35.470001]
 [35.305   ]
 [35.610001]
 [35.875   ]

In [31]:
print(volume_2017)

[[1.151276e+08]
 [8.447240e+07]
 [8.877440e+07]
 [1.270076e+08]
 [1.342476e+08]
 [9.784840e+07]
 [1.103544e+08]
 [1.083448e+08]
 [1.044476e+08]
 [1.377592e+08]
 [9.485200e+07]
 [1.023892e+08]
 [1.303916e+08]
 [8.820080e+07]
 [9.284400e+07]
 [1.295104e+08]
 [1.053504e+08]
 [8.225160e+07]
 [1.215100e+08]
 [1.968040e+08]
 [4.479400e+08]
 [1.348416e+08]
 [9.802920e+07]
 [1.073836e+08]
 [1.527352e+08]
 [9.201640e+07]
 [1.133996e+08]
 [8.026200e+07]
 [9.214160e+07]
 [1.329048e+08]
 [1.424924e+08]
 [9.033840e+07]
 [8.879280e+07]
 [9.802880e+07]
 [8.334760e+07]
 [8.315280e+07]
 [8.710640e+07]
 [8.102960e+07]
 [9.393160e+07]
 [1.456584e+08]
 [1.048440e+08]
 [8.443240e+07]
 [8.700000e+07]
 [6.978520e+07]
 [7.482880e+07]
 [8.862360e+07]
 [7.845120e+07]
 [6.968680e+07]
 [6.123640e+07]
 [1.027672e+08]
 [7.692800e+07]
 [1.755400e+08]
 [8.616800e+07]
 [1.581196e+08]
 [1.034408e+08]
 [8.138520e+07]
 [8.958240e+07]
 [9.430040e+07]
 [1.334992e+08]
 [1.167600e+08]
 [8.482920e+07]
 [7.864680e+07]
 [7.9942

In [32]:
volume_open_2016 = y[:,[1, 6]]
volume_open_2017 = z[:,[1, 6]]

In [33]:
print(volume_open_2016)

[[1.02610001e+02 6.76494000e+07]
 [1.05750000e+02 5.57910000e+07]
 [1.00559998e+02 6.84574000e+07]
 [9.86800000e+01 8.10944000e+07]
 [9.85500030e+01 7.07980000e+07]
 [9.89700010e+01 4.97394000e+07]
 [1.00550003e+02 4.91542000e+07]
 [1.00320000e+02 6.24396000e+07]
 [9.79599990e+01 6.31701000e+07]
 [9.61999970e+01 7.90100000e+07]
 [9.84100040e+01 5.30877000e+07]
 [9.50999980e+01 7.23344000e+07]
 [9.70599980e+01 5.21615000e+07]
 [9.86299970e+01 6.58005000e+07]
 [1.01519997e+02 5.17945000e+07]
 [9.99300000e+01 7.50770000e+07]
 [9.60400010e+01 1.33369700e+08]
 [9.37900010e+01 5.56788000e+07]
 [9.47900010e+01 6.44165000e+07]
 [9.64700010e+01 4.09435000e+07]
 [9.54199980e+01 3.73572000e+07]
 [9.50000000e+01 4.59643000e+07]
 [9.58600010e+01 4.64717000e+07]
 [9.65199970e+01 4.64181000e+07]
 [9.31299970e+01 5.40214000e+07]
 [9.42900010e+01 4.43312000e+07]
 [9.59199980e+01 4.23436000e+07]
 [9.37900010e+01 5.00747000e+07]
 [9.41900020e+01 4.03514000e+07]
 [9.50199970e+01 4.90579000e+07]
 [9.666999

In [34]:
print(volume_open_2017)

[[2.8950001e+01 1.1512760e+08]
 [2.8962500e+01 8.4472400e+07]
 [2.8980000e+01 8.8774400e+07]
 [2.9195000e+01 1.2700760e+08]
 [2.9487499e+01 1.3424760e+08]
 [2.9692499e+01 9.7848400e+07]
 [2.9684999e+01 1.1035440e+08]
 [2.9725000e+01 1.0834480e+08]
 [2.9777500e+01 1.0444760e+08]
 [2.9584999e+01 1.3775920e+08]
 [3.0000000e+01 9.4852000e+07]
 [2.9850000e+01 1.0238920e+08]
 [3.0112499e+01 1.3039160e+08]
 [3.0000000e+01 8.8200800e+07]
 [2.9887501e+01 9.2844000e+07]
 [3.0105000e+01 1.2951040e+08]
 [3.0417500e+01 1.0535040e+08]
 [3.0535000e+01 8.2251600e+07]
 [3.0232500e+01 1.2151000e+08]
 [3.0287500e+01 1.9680400e+08]
 [3.1757500e+01 4.4794000e+08]
 [3.1995001e+01 1.3484160e+08]
 [3.2077499e+01 9.8029200e+07]
 [3.2282501e+01 1.0738360e+08]
 [3.2634998e+01 1.5273520e+08]
 [3.2837502e+01 9.2016400e+07]
 [3.2912498e+01 1.1339960e+08]
 [3.3115002e+01 8.0262000e+07]
 [3.3270000e+01 9.2141600e+07]
 [3.3367500e+01 1.3290480e+08]
 [3.3880001e+01 1.4249240e+08]
 [3.3917500e+01 9.0338400e+07]
 [3.3775

In [35]:
sum_2016 = volume_open_2016.sum(axis = 0)
sum_2017 = volume_open_2017.sum(axis = 0)

In [36]:
print(sum_2016)

[2.6102860e+04 9.6349957e+09]


In [37]:
print(sum_2017)

[9.39778751e+03 2.71391064e+10]


In [38]:
new_sum_2016 = np.array(sum_2016, dtype = np.int64)

In [39]:
print(new_sum_2016)

[     26102 9634995700]


In [40]:
new_sum_2017 = np.array(sum_2017, dtype = np.int64)

In [41]:
print(new_sum_2017)

[       9397 27139106400]


In [46]:
change = np.subtract(volume_open_2016, volume_open_2017)
change

array([[ 7.3660000e+01, -4.7478200e+07],
       [ 7.6787500e+01, -2.8681400e+07],
       [ 7.1579998e+01, -2.0317000e+07],
       [ 6.9485000e+01, -4.5913200e+07],
       [ 6.9062504e+01, -6.3449600e+07],
       [ 6.9277502e+01, -4.8109000e+07],
       [ 7.0865004e+01, -6.1200200e+07],
       [ 7.0595000e+01, -4.5905200e+07],
       [ 6.8182499e+01, -4.1277500e+07],
       [ 6.6614998e+01, -5.8749200e+07],
       [ 6.8410004e+01, -4.1764300e+07],
       [ 6.5249998e+01, -3.0054800e+07],
       [ 6.6947499e+01, -7.8230100e+07],
       [ 6.8629997e+01, -2.2400300e+07],
       [ 7.1632496e+01, -4.1049500e+07],
       [ 6.9825000e+01, -5.4433400e+07],
       [ 6.5622501e+01,  2.8019300e+07],
       [ 6.3255001e+01, -2.6572800e+07],
       [ 6.4557501e+01, -5.7093500e+07],
       [ 6.6182501e+01, -1.5586050e+08],
       [ 6.3662498e+01, -4.1058280e+08],
       [ 6.3004999e+01, -8.8877300e+07],
       [ 6.3782502e+01, -5.1557500e+07],
       [ 6.4237496e+01, -6.0965500e+07],
       [ 6.04949

In [48]:
change.sum(axis = 0)[1]

-17504110700.0

In [45]:
print(new_sum_2016[1]- new_sum_2017[1])


-17504110700


In [49]:
print(new_sum_2016[1], new_sum_2017[1])


9634995700 27139106400


In [50]:
print(change)
np.set_printoptions(formatter={'float': '{:6.2f}'.format})
print("########################################")
print(change)

[[ 7.3660000e+01 -4.7478200e+07]
 [ 7.6787500e+01 -2.8681400e+07]
 [ 7.1579998e+01 -2.0317000e+07]
 [ 6.9485000e+01 -4.5913200e+07]
 [ 6.9062504e+01 -6.3449600e+07]
 [ 6.9277502e+01 -4.8109000e+07]
 [ 7.0865004e+01 -6.1200200e+07]
 [ 7.0595000e+01 -4.5905200e+07]
 [ 6.8182499e+01 -4.1277500e+07]
 [ 6.6614998e+01 -5.8749200e+07]
 [ 6.8410004e+01 -4.1764300e+07]
 [ 6.5249998e+01 -3.0054800e+07]
 [ 6.6947499e+01 -7.8230100e+07]
 [ 6.8629997e+01 -2.2400300e+07]
 [ 7.1632496e+01 -4.1049500e+07]
 [ 6.9825000e+01 -5.4433400e+07]
 [ 6.5622501e+01  2.8019300e+07]
 [ 6.3255001e+01 -2.6572800e+07]
 [ 6.4557501e+01 -5.7093500e+07]
 [ 6.6182501e+01 -1.5586050e+08]
 [ 6.3662498e+01 -4.1058280e+08]
 [ 6.3004999e+01 -8.8877300e+07]
 [ 6.3782502e+01 -5.1557500e+07]
 [ 6.4237496e+01 -6.0965500e+07]
 [ 6.0494999e+01 -9.8713800e+07]
 [ 6.1452499e+01 -4.7685200e+07]
 [ 6.3007500e+01 -7.1056000e+07]
 [ 6.0674999e+01 -3.0187300e+07]
 [ 6.0920002e+01 -5.1790200e+07]
 [ 6.1652497e+01 -8.3846900e+07]
 [ 6.27899

In [52]:
combined_years = np.concatenate((volume_open_2016, volume_open_2017))
combined_years

array([[102.61, 67649400.00],
       [105.75, 55791000.00],
       [100.56, 68457400.00],
       [ 98.68, 81094400.00],
       [ 98.55, 70798000.00],
       [ 98.97, 49739400.00],
       [100.55, 49154200.00],
       [100.32, 62439600.00],
       [ 97.96, 63170100.00],
       [ 96.20, 79010000.00],
       [ 98.41, 53087700.00],
       [ 95.10, 72334400.00],
       [ 97.06, 52161500.00],
       [ 98.63, 65800500.00],
       [101.52, 51794500.00],
       [ 99.93, 75077000.00],
       [ 96.04, 133369700.00],
       [ 93.79, 55678800.00],
       [ 94.79, 64416500.00],
       [ 96.47, 40943500.00],
       [ 95.42, 37357200.00],
       [ 95.00, 45964300.00],
       [ 95.86, 46471700.00],
       [ 96.52, 46418100.00],
       [ 93.13, 54021400.00],
       [ 94.29, 44331200.00],
       [ 95.92, 42343600.00],
       [ 93.79, 50074700.00],
       [ 94.19, 40351400.00],
       [ 95.02, 49057900.00],
       [ 96.67, 44863200.00],
       [ 98.84, 39021000.00],
       [ 96.00, 35374200.00],
       [ 

In [55]:
with open("AAPL_2016_2017.csv", 'w', newline="") as newfile:
    writer = csv.writer(newfile)
    writer.writerow(["Open Price", "Volume"])
    writer.writerows(combined_years)
    

In [56]:
np.savetxt("AAPL_2016_2017.txt",combined_years, fmt = "%10.2f", delimiter = ",")