In [2]:
import numpy as np
import pandas as pd

In [8]:
np.set_printoptions(formatter={'float': '{:6.2f}'.format})

In [9]:
a = np.genfromtxt('AAPL-2016.csv', delimiter=',', skip_header = 1)
b = np.genfromtxt('AAPL-2017.csv', delimiter=',', skip_header = 1)

In [10]:
january = a[:20]

In [11]:
january

array([[   nan, 102.61, 105.37, 102.00, 105.35, 100.27, 67649400.00],
       [   nan, 105.75, 105.85, 102.41, 102.71,  97.76, 55791000.00],
       [   nan, 100.56, 102.37,  99.87, 100.70,  95.85, 68457400.00],
       [   nan,  98.68, 100.13,  96.43,  96.45,  91.80, 81094400.00],
       [   nan,  98.55,  99.11,  96.76,  96.96,  92.29, 70798000.00],
       [   nan,  98.97,  99.06,  97.34,  98.53,  93.78, 49739400.00],
       [   nan, 100.55, 100.69,  98.84,  99.96,  95.14, 49154200.00],
       [   nan, 100.32, 101.19,  97.30,  97.39,  92.70, 62439600.00],
       [   nan,  97.96, 100.48,  95.74,  99.52,  94.73, 63170100.00],
       [   nan,  96.20,  97.71,  95.36,  97.13,  92.45, 79010000.00],
       [   nan,  98.41,  98.65,  95.50,  96.66,  92.00, 53087700.00],
       [   nan,  95.10,  98.19,  93.42,  96.79,  92.13, 72334400.00],
       [   nan,  97.06,  97.88,  94.94,  96.30,  91.66, 52161500.00],
       [   nan,  98.63, 101.46,  98.37, 101.42,  96.53, 65800500.00],
       [   nan, 101.

In [16]:
january[0][6] = 100
january


array([[   nan, 102.61, 105.37, 102.00, 105.35, 100.27, 100.00],
       [   nan, 105.75, 105.85, 102.41, 102.71,  97.76, 55791000.00],
       [   nan, 100.56, 102.37,  99.87, 100.70,  95.85, 68457400.00],
       [   nan,  98.68, 100.13,  96.43,  96.45,  91.80, 81094400.00],
       [   nan,  98.55,  99.11,  96.76,  96.96,  92.29, 70798000.00],
       [   nan,  98.97,  99.06,  97.34,  98.53,  93.78, 49739400.00],
       [   nan, 100.55, 100.69,  98.84,  99.96,  95.14, 49154200.00],
       [   nan, 100.32, 101.19,  97.30,  97.39,  92.70, 62439600.00],
       [   nan,  97.96, 100.48,  95.74,  99.52,  94.73, 63170100.00],
       [   nan,  96.20,  97.71,  95.36,  97.13,  92.45, 79010000.00],
       [   nan,  98.41,  98.65,  95.50,  96.66,  92.00, 53087700.00],
       [   nan,  95.10,  98.19,  93.42,  96.79,  92.13, 72334400.00],
       [   nan,  97.06,  97.88,  94.94,  96.30,  91.66, 52161500.00],
       [   nan,  98.63, 101.46,  98.37, 101.42,  96.53, 65800500.00],
       [   nan, 101.52, 1

In [15]:
a

array([[   nan, 102.61, 105.37, ..., 105.35, 100.27, 100.00],
       [   nan, 105.75, 105.85, ..., 102.71,  97.76, 55791000.00],
       [   nan, 100.56, 102.37, ..., 100.70,  95.85, 68457400.00],
       ...,
       [   nan, 115.59, 116.52, ..., 116.52, 113.37, 14249500.00],
       [   nan, 116.52, 117.80, ..., 117.26, 114.09, 18296900.00],
       [   nan, 117.52, 118.02, ..., 116.76, 113.61, 20905900.00]])

In [17]:
print(a[:5])

[[   nan 102.61 105.37 102.00 105.35 100.27 100.00]
 [   nan 105.75 105.85 102.41 102.71  97.76 55791000.00]
 [   nan 100.56 102.37  99.87 100.70  95.85 68457400.00]
 [   nan  98.68 100.13  96.43  96.45  91.80 81094400.00]
 [   nan  98.55  99.11  96.76  96.96  92.29 70798000.00]]


In [18]:
maximum = a.max(axis=0)
maximum[4]

118.25

In [19]:
vertical_slice = a[:,2:4]
vertical_slice[:5]

array([[105.37, 102.00],
       [105.85, 102.41],
       [102.37,  99.87],
       [100.13,  96.43],
       [ 99.11,  96.76]])