In [1]:
import numpy as np

In [7]:
a = np.array([1,2,3])
print('type(a): ', type(a))
print('a.shape: ', a.shape)
print(a[0], a[1])

a[0] = 5
print(a)

type(a):  <class 'numpy.ndarray'>
a.shape:  (3,)
1 2
[5 2 3]


In [12]:
b = np.array([[1,2,3], [4,5,6]])
print(b.shape)
print(b[0,0])
print(b)

(2, 3)
1
[[1 2 3]
 [4 5 6]]


In [14]:
c = np.array([1,2,3], dtype = np.float64)

d = np.array([4,5,6], dtype = np.int32)

In [21]:
my_int = np.dtype(np.int16)
print(my_int)

lst = [
    [1.32, 2.4343, 3.4343],
    [4.45, 5.4346, 6.3434],
    [7.34, 8.4334, 9.4343]
]

A = np.array(lst, dtype = np.int16)
print(A)

int16
(3, 3)


In [20]:
samples = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(samples)

print("Data type: ", samples.dtype)
print("Shape: ", samples.shape)
print("Size: ", samples.size)
print("Stride: ", samples.strides)


[ 1  2  3  4  5  6  7  8  9 10 11 12]
Data type:  int32
Shape:  (12,)
Size:  12
Stride:  (4,)


In [29]:
a = np.arange(1, 5)
print(a)

b = np.arange(start = 1, stop = 5)
print(b)

c = np.arange(1, 5, 0.3)
print(c)

d = np.arange(1, 10, 2.9, int)
print(d)

[1 2 3 4]
[1 2 3 4]
[1.  1.3 1.6 1.9 2.2 2.5 2.8 3.1 3.4 3.7 4.  4.3 4.6 4.9]
[1 3 5 7]


In [30]:
x = np.array(42)
print(x)
print(x.shape)
print(x.ndim)
#np.ndim(x)

42
()
0


In [32]:
f = np.array([1,2,3])
print(f)
print(f.dtype)
print(f.ndim)

[1 2 3]
int32
1


In [35]:
e = np.ones((2,3))
print(e)

f = np.zeros((2,3), dtype = int)
print(f)

[[1. 1. 1.]
 [1. 1. 1.]]
[[0 0 0]
 [0 0 0]]


In [36]:
f = np.array([1,2,3])
x = np.ones_like(f)
print(x)

[1 1 1]


In [40]:
f = np.array([1,2,3], order = 'A')
g = f.copy()

print(g)

[1 2 3]


In [41]:
x = np.identity(4)
print(x)

y = np.identity(5, dtype = int)
print(y)

z = np.identity(5, dtype = int)
print(z)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [43]:
x = np.eye(3,5,k=1,dtype = float)
print(x)

[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]
